apiVersion: v1
kind: Pod
metadata:
  name: local-postgres
  namespace: prod
  labels:
    app: local-postgres
spec:
  restartPolicy: Never
  containers:
    - name: postgres
      image: postgres:15
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: "courm_order"
        - name: POSTGRES_USER
          value: "courmadmin"
        - name: POSTGRES_PASSWORD
          value: "courmadmin1234!"
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: local-postgres
  namespace: prod
spec:
  selector:
    app: local-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
