## Local docker-compose env mapping
config:
  springKafkaBootstrapServers: "courm-kafka.courm-kafka.svc.cluster.local:9092"
  kafkaBootstrapServers: "courm-kafka.courm-kafka.svc.cluster.local:9092"
  serverPort: "8080"
  springDatasourceUrl: "jdbc:postgresql://courm-rds-order-prod.c9iosg68k3c4.ap-northeast-2.rds.amazonaws.com:5432/courm_order"
  awsCognitoJwkSetUri: "https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_HmqfrWP3T/.well-known/jwks.json"
  dbHost: "courm-rds-order-prod.c9iosg68k3c4.ap-northeast-2.rds.amazonaws.com"
  dbPort: "5432"
  dbName: "courm_order"

secret:
  dbUsername: "courmadmin"
  dbPassword: "courmadmin1234!"

## secret
imagePullSecrets:
  - name: ecr-secret

## gateway api
route:
  enabled: true
  gatewayName: prod-gw
  gatewayNamespace: istio-system
  path: /api/v2/payments
  pathType: PathPrefix
  weight: 1
  hostnames: []

service:
  port: 80
  targetPort: 8080
  type: ClusterIP

image:
  repository: 900808296075.dkr.ecr.ap-northeast-2.amazonaws.com/goorm-payment
  tag: "9-37ee6046"

replicas: 1

## Argo Rollouts Strategy
strategy:
  type: blueGreen
  blueGreen:
    autoPromotionEnabled: true
    scaleDownDelaySeconds: 300

## Resource limits (Guaranteed QoS: requests = limits → Evict 방지)
resources:
  requests:
    memory: "1Gi"
    cpu: "1"
  limits:
    memory: "1Gi"
    cpu: "1"

revisionHistoryLimit: 3

## HPA (Auto-Scaling)
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60

## Monitoring
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

# Tempo
otel:
  enabled: true
  serviceName: payment-service
  otlpEndpoint: "http://otel-collector.monitoring.svc.cluster.local:4318" # Assuming we will deploy collector there or use simpler setup
  otlpProtocol: "http/protobuf"
  tracesExporter: "otlp"
  metricsExporter: "none"
  logsExporter: "none"
  javaAgent:
    jarPath: "/otel/opentelemetry-javaagent.jar"

## Istio DestinationRule
## (Circuit Breaker)
destinationRule:
  enabled: true
  connectionPool:
    tcp:
      maxConnections: 100
    http:
      http1MaxPendingRequests: 10
      maxRequestsPerConnection: 1
  outlierDetection:
    consecutive5xxErrors: 5
    interval: 10s
    baseEjectionTime: 30s
    maxEjectionPercent: 100

# JVM 컨테이너 인식 옵션 및 메모리 효율화
javaToolOptions: >-
  -javaagent:/otel/opentelemetry-javaagent.jar
  -Dotel.resource.attributes=service.name=payment-service
  -Dotel.exporter.otlp.endpoint=http://otel-collector.monitoring.svc.cluster.local:4318
  -Dspring.kafka.bootstrap-servers=courm-kafka.courm-kafka.svc.cluster.local:9092
  -XX:+UseContainerSupport
  -XX:MaxRAMPercentage=75.0
  -XX:+ExitOnOutOfMemoryError
