{{- if .Values.hpa.enabled }}
{{- $metrics := .Values.hpa.metrics }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "order-service.fullname" . }}-hpa
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "order-service.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas | default 2 }}
  maxReplicas: {{ .Values.hpa.maxReplicas | default 10 }}
{{- if .Values.hpa.behavior }}
  behavior:
{{ toYaml .Values.hpa.behavior | nindent 4 }}
{{- else }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
{{- end }}
  metrics:
{{- if $metrics }}
{{ toYaml $metrics | nindent 2 }}
{{- else }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetCPU | default 60 }}
{{- end }}
{{- end }}
