apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-service.fullname" . }}-active
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "order-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
