{{- if .Values.destinationRule.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "courm-app.fullname" . }}-cb
  namespace: {{ .Release.Namespace }}
spec:
  # Blue/Green 배포 시 Active 서비스(운영중인 서비스)로 트래픽 제어
  host: {{ include "courm-app.fullname" . }}-active
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: {{ .Values.destinationRule.connectionPool.tcp.maxConnections }}
      http:
        http1MaxPendingRequests: {{ .Values.destinationRule.connectionPool.http.http1MaxPendingRequests }}
        maxRequestsPerConnection: {{ .Values.destinationRule.connectionPool.http.maxRequestsPerConnection }}
    outlierDetection:
      consecutive5xxErrors: {{ .Values.destinationRule.outlierDetection.consecutive5xxErrors }}
      interval: {{ .Values.destinationRule.outlierDetection.interval }}
      baseEjectionTime: {{ .Values.destinationRule.outlierDetection.baseEjectionTime }}
      maxEjectionPercent: {{ .Values.destinationRule.outlierDetection.maxEjectionPercent }}
{{- end }}
