apiVersion: v1
kind: Secret
metadata:
  name: {{ include "courm-app.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "courm-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  {{- with .Values.secret }}
  {{- with .dbUsername }}
  DB_USERNAME: {{ . | quote }}
  {{- end }}
  {{- with .dbPassword }}
  DB_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .awsCognitoClientSecret }}
  AWS_COGNITO_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.redis }}
  {{- with .username }}
  REDIS_USERNAME: {{ . | quote }}
  SPRING_REDIS_USERNAME: {{ . | quote }}
  SPRING_DATA_REDIS_USERNAME: {{ . | quote }}
  {{- end }}
  {{- with .password }}
  REDIS_PASSWORD: {{ . | quote }}
  SPRING_REDIS_PASSWORD: {{ . | quote }}
  SPRING_DATA_REDIS_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- if hasKey . "sslEnabled" }}
  SPRING_REDIS_SSL_ENABLED: {{ .sslEnabled | toString | quote }}
  SPRING_DATA_REDIS_SSL_ENABLED: {{ .sslEnabled | toString | quote }}
  {{- end }}
  {{- end }}

