apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-service.fullname" . }}-secret
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secret.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
