apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cart-service.fullname" . }}-config
  labels:
    {{- include "cart-service.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.springDatasourceUrl | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.profile | default "prod" | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  SPRING_KAFKA_CONSUMER_GROUP_ID: {{ .Values.kafka.consumerGroupId | quote }}
  KAFKA_ORDER_TOPIC: {{ .Values.kafka.orderTopic | quote }}
  KAFKA_PAYMENT_TOPIC: {{ .Values.kafka.paymentTopic | quote }}
  KAFKA_PRODUCT_TOPIC: {{ .Values.kafka.productTopic | quote }}
  SPRING_DATA_REDIS_HOST: {{ .Values.redis.host | quote }}
  SPRING_REDIS_HOST: {{ .Values.redis.host | quote }}
  SPRING_DATA_REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  PRODUCT_SERVICE_URL: {{ .Values.product.serviceUrl | quote }}
  COGNITO_JWK_SET_URI: {{ .Values.cognito.jwkSetUri | quote }}
  AWS_COGNITO_JWK_SET_URI: {{ .Values.cognito.awsJwkSetUri | default .Values.cognito.jwkSetUri | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
