apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cart-service.fullname" . }}-redis
  labels:
    {{- include "cart-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATA_REDIS_USERNAME: {{ .Values.redis.username | quote }}
  SPRING_REDIS_USERNAME: {{ .Values.redis.username | quote }}
  REDIS_USERNAME: {{ .Values.redis.username | quote }}
  SPRING_DATA_REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  SPRING_REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  SPRING_DATA_REDIS_SSL_ENABLED: {{ .Values.redis.sslEnabled | toString | quote }}
  SPRING_REDIS_SSL_ENABLED: {{ .Values.redis.sslEnabled | toString | quote }}
