apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cart-service.fullname" . }}-secret
  labels:
    {{- include "cart-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
