## env
env:
  - name: DB_HOST
    value: "postgresql"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "ecommerce"
  - name: SPRING_DATASOURCE_USERNAME
    value: "postgres"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "postgres"
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: "courm-kafka.courm-kafka.svc.cluster.local:9092"
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "user-service-group"
  - name: KAFKA_USER_TOPIC
    value: "user-events"


## secret
imagePullSecrets:
  - name: ecr-secret

## gateway api
route:
  enabled: true
  gatewayName: prod-gw
  gatewayNamespace: istio-system
  path: /api/v2/user
  pathType: PathPrefix
  weight: 1
  hostnames: []

service:
  port: 80
  targetPort: 8080
  type: ClusterIP

image:
  repository: 900808296075.dkr.ecr.ap-northeast-2.amazonaws.com/goorm-user
  tag: "21-7ed52502"

replicas: 1

## Argo Rollouts Strategy
strategy:
  type: blueGreen
  blueGreen:
    autoPromotionEnabled: true
    scaleDownDelaySeconds: 300

## Resource limits
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

revisionHistoryLimit: 3

## Monitoring
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

# Tempo
otel:
  enabled: false
  serviceName: user-service
  otlpEndpoint: "http://otel-collector.monitoring.svc.cluster.local:4318"
  otlpProtocol: "http/protobuf"
  tracesExporter: "otlp"
  metricsExporter: "none"
  logsExporter: "none"
  javaAgent:
    jarPath: "/otel/opentelemetry-javaagent.jar"

javaToolOptions: ""   # 필요하면 "-Xms256m -Xmx512m" 같은거 여기에
