profile: dev

replicas: 2
revisionHistoryLimit: 3

# ------------------------
# Image
# ------------------------
image:
  repository: 900808296075.dkr.ecr.ap-northeast-2.amazonaws.com/goorm-cart
  tag: "9-eeb107bd"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-secret

# ------------------------
# Service
# ------------------------
service:
  port: 80
  targetPort: 8080
  type: ClusterIP


# ------------------------
# Redis
# ------------------------
redis:
  host: local-redis.prod.svc.cluster.local
  port: 6379

# ------------------------
# Kafka
# ------------------------
kafka:
  bootstrapServers: courm-kafka.courm-kafka.svc.cluster.local:9092
  consumerGroupId: cart-service-group
  orderTopic: order-events

# ------------------------
# Cognito
# ------------------------
#cognito:
#  region: ap-northeast-2
#  userPoolId: ap-northeast-2_XXXXX

# ------------------------
# Gateway API
# ------------------------
route:
  enabled: true
  gatewayName: prod-gw
  gatewayNamespace: istio-system
  path: /api/v2/cart
  pathType: PathPrefix
  weight: 1
  hostnames: []

# ------------------------
# Argo Rollouts
# ------------------------
strategy:
  type: blueGreen
  blueGreen:
    autoPromotionEnabled: true
    scaleDownDelaySeconds: 300

# ------------------------
# Resources
# ------------------------
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# ------------------------
# Prometheus
# ------------------------
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

# ------------------------
# OpenTelemetry (Tempo)
# ------------------------
otel:
  enabled: false
  serviceName: cart-service
  otlpEndpoint: "http://otel-collector.monitoring.svc.cluster.local:4318"
  otlpProtocol: "http/protobuf"
  tracesExporter: "otlp"
  metricsExporter: "none"
  logsExporter: "none"
  javaAgent:
    jarPath: "/otel/opentelemetry-javaagent.jar"

javaToolOptions: >-
  -Dspring.kafka.bootstrap-servers=courm-kafka.courm-kafka.svc.cluster.local:9092
  -Dspring.data.redis.host=local-redis.prod.svc.cluster.local
  -Dspring.datasource.hikari.maximum-pool-size=20
  -Dspring.datasource.hikari.connection-timeout=5000
  -XX:+UseContainerSupport
  -XX:MaxRAMPercentage=75.0
  -XX:+ExitOnOutOfMemoryError
logLevel: INFO
