apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secret.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  AWS_COGNITO_CLIENT_SECRET: {{ .Values.secret.awsCognitoClientSecret | quote }}
