## Local docker-compose env mapping
config:
  springKafkaBootstrapServers: "courm-kafka.courm-kafka.svc.cluster.local:9092"
  kafkaBootstrapServers: "courm-kafka.courm-kafka.svc.cluster.local:9092"
  userServiceUrl: "http://user:8080"
  productServiceUrl: "http://product:8080"
  serverPort: "8080"
  springDatasourceUrl: "jdbc:postgresql://postgresql:5432/ecommerce"
  awsCognitoJwkSetUri: "https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_HmqfrWP3T/.well-known/jwks.json"
  dbHost: "postgresql"
  dbPort: "5432"
  dbName: "ecommerce"

secret:
  dbUsername: "postgres"
  dbPassword: "postgres"

imagePullSecrets:
  - name: ecr-secret

## gateway api
route:
  enabled: true
  gatewayName: prod-gw
  gatewayNamespace: istio-system

  # /api 아래는 전부 Istio로
  path: /api
  pathType: PathPrefix
  weight: 1

  # Host 기반 라우팅
  hostnames:
    - order.example.com

  # /api prefix 제거해서 앱에 원래 경로로 전달
  # /api/actuator/health  ->  /actuator/health
  # /api/v2/orders/...    ->  /v2/orders/... (앱이 /api/v2/...를 기대하면 아래 replace를 "/api"로 바꾸면 됨)
  urlRewrite:
    enabled: true
    replacePrefixMatch: "/"

service:
  port: 80
  targetPort: 8080
  type: ClusterIP

image:
  repository: 900808296075.dkr.ecr.ap-northeast-2.amazonaws.com/goorm-order
  tag: "4-365b3684"

replicas: 1

strategy:
  type: blueGreen
  blueGreen:
    autoPromotionEnabled: true
    scaleDownDelaySeconds: 300

resources:
  requests:
    memory: "768Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

revisionHistoryLimit: 3

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

otel:
  enabled: false
  serviceName: order-service
  otlpEndpoint: "http://otel-collector.monitoring.svc.cluster.local:4318"
  otlpProtocol: "http/protobuf"
  tracesExporter: "otlp"
  metricsExporter: "none"
  logsExporter: "none"
  javaAgent:
    jarPath: "/otel/opentelemetry-javaagent.jar"

javaToolOptions: >-
  -Dspring.kafka.bootstrap-servers=courm-kafka.courm-kafka.svc.cluster.local:9092
  -XX:+UseContainerSupport
  -XX:MaxRAMPercentage=75.0
  -XX:+ExitOnOutOfMemoryError
